attempt to add Portage(emerge) and some fixes for apk (#16)
* attempt to add Portage(emerge) and some fixes for apk

* use if statements for list

* use if statements for list #2

Co-authored-by: tanmatsu <tanmatsu@tutanota.com>

diff --git a/cpm b/cpm
--- a/cpm
+++ b/cpm
@@ -120,12 +120,12 @@ _apk() {
     case "$OP" in
 	install) $SUDO apk add "$@";;
 	remove)  $SUDO apk del "$@";;
-	list)    $SUDO apk info -vv;;
-	count)   $SUDO apk info --vv || tot;;
+	list)    apk -vv info;;
+	count)   apk -vv info || tot;;
 	update)  $SUDO apk update;;
 	upgrade) $SUDO apk upgrade;;
-	search)  $SUDO apk search -v "$1";;
-	show)    $SUDO apk search "$1";;
+	search)  apk search -v "$1";;
+	show)    apk search "$1";;
 	clean)   $SUDO apk cache clean;;
     esac
 }
@@ -141,6 +141,32 @@ _apt() {
         search) apt search "$1";;
         show) apt show "$1";;
         clean) $SUDO apt autoremove;;
+    esac
+}
+
+_portage() {
+    case "$OP" in
+	install) $SUDO emerge -atv "$@";;
+	remove)  $SUDO emerge -avc "$@";;
+	list)    if has qlist; then
+		 	qlist -IRv
+	 	 else
+		 	>&2 echo "Could not find qlist"
+			exit 1
+		 fi
+		 ;;
+	count)   if has eix; then
+			eix --world | tot
+		 else
+			>&2 echo "Could not find eix"
+			exit 1
+		 fi
+		 ;;
+	update)  $SUDO emerge --sync;;
+	upgrade) $SUDO emerge -uDU --keep-going --with-bdeps=y @world;;
+	search)  emerge -s "$@";;
+	show)    emerge -s "$@";;
+	clean)   $SUDO emerge --depclean -v;;
     esac
 }
 
@@ -220,6 +246,9 @@ if   has apk; then
 elif has apt; then
     # debian/ubuntu
     _apt "$@"
+elif has emerge; then
+    # gentoo
+    _portage "$@"
 elif has dnf; then
     # fedora
     _dnf "$@"
